asset_path: model/right.urdf
usd_dir: model/usd
usd_file_name: wujihand
force_usd_conversion: true
make_instanceable: true
fix_base: true
root_link_name: palm_link
link_density: 1
merge_fixed_joints: true
convert_mimic_joints_to_normal_joints: false
joint_drive:
  drive_type: force
  target_type: position
  gains:
    stiffness:
      finger(1|2|3|4|5)_joint(1|2): 2
      finger(1|2|3|4|5)_joint3: 1
      finger(1|2|3|4|5)_joint4: 0.8
    damping:
      finger.*_joint(1|2): 0.05
      finger.*_joint(3|4): 0.03
collider_type: convex_hull
self_collision: true
replace_cylinders_with_capsules: false
collision_from_visuals: false
func: isaaclab.sim.spawners.from_files.from_files:spawn_from_urdf
visible: true
semantic_tags: null
copy_from_source: true
mass_props: null
deformable_props: null
rigid_props:
  rigid_body_enabled: null
  kinematic_enabled: null
  disable_gravity: false
  linear_damping: 0.0
  angular_damping: 0.0
  max_linear_velocity: 1000.0
  max_angular_velocity: 1000.0
  max_depenetration_velocity: 10.0
  max_contact_impulse: null
  enable_gyroscopic_forces: null
  retain_accelerations: null
  solver_position_iteration_count: null
  solver_velocity_iteration_count: null
  sleep_threshold: null
  stabilization_threshold: null
collision_props: null
activate_contact_sensors: true
scale: null
articulation_props:
  articulation_enabled: null
  enabled_self_collisions: true
  solver_position_iteration_count: 20
  solver_velocity_iteration_count: 10
  sleep_threshold: null
  stabilization_threshold: null
  fix_root_link: null
fixed_tendons_props: null
spatial_tendons_props: null
joint_drive_props: null
visual_material_path: material
visual_material: null
##
# Generated by UrdfConverter on 2025-11-06 at 09:14:20.
##
